# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - 1.11.x
#  - 1.12.x

install:
#  - go get github.com/mattn/goveralls
  - go get -u golang.org/x/lint/golint

script:
  - make lint
  - make test
  - make race
